INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Afghanistan','AF','+93',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Aland Islands','AX','+358',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Albania','AL','+355',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Algeria','DZ','+213',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'American Samoa','AS','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Andorra','AD','+376',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Angola','AO','+244',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Anguilla','AI','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Antarctica','AQ','',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Antigua and Barbuda','AG','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Argentina','AR','+54',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Armenia','AM','+374',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Aruba','AW','+297',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Australia','AU','+61',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Austria','AT','+43',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Azerbaijan','AZ','+994',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Bahamas','BS','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Bahrain','BH','+973',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Bangladesh','BD','+880',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Barbados','BB','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Belarus','BY','+375',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Belgium','BE','+32',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Belize','BZ','+501',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Benin','BJ','+229',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Bermuda','BM','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Bhutan','BT','+975',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Bolivia','BO','+591',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Bonaire, Sint Eustatius and Saba','BQ','+599',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Bosnia and Herzegovina','BA','+387',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Botswana','BW','+267',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Bouvet Island','BV','',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Brazil','BR','+55',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'British Indian Ocean Territory','IO','',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Brunei','BN','+673',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Bulgaria','BG','+359',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Burkina Faso','BF','+226',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Burundi','BI','+257',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Cambodia','KH','+855',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Cameroon','CM','+237',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Canada','CA','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Cape Verde','CV','+238',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Cayman Islands','KY','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Central African Republic','CF','+236',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Chad','TD','+235',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Chile','CL','+56',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'China','CN','+86',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Christmas Island','CX','+61',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Cocos (Keeling) Islands','CC','+61',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Colombia','CO','+57',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Comoros','KM','+269',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Congo','CG','+242',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Cook Islands','CK','+682',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Costa Rica','CR','+506',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Ivory Coast','CI','+225',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Croatia','HR','+385',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Cuba','CU','+53',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Curacao','CW','+599',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Cyprus','CY','+357',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Czech Republic','CZ','+420',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Denmark','DK','+45',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Djibouti','DJ','+253',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Dominica','DM','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Dominican Republic','DO','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Ecuador','EC','+593',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Egypt','EG','+20',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'El Salvador','SV','+503',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Equatorial Guinea','GQ','+240',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Eritrea','ER','+291',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Estonia','EE','+372',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Ethiopia','ET','+251',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Falkland Islands','FK','+500',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Faroe Islands','FO','+298',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Fiji','FJ','+679',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Finland','FI','+358',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'France','FR','+33',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'French Guiana','GF','+594',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'French Polynesia','PF','+689',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'French Southern Territories','TF','',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Gabon','GA','+241',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Gambia','GM','+220',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Georgia','GE','+995',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Germany','DE','+49',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Ghana','GH','+233',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Gibraltar','GI','+350',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Greece','GR','+30',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Greenland','GL','+299',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Grenada','GD','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Guadeloupe','GP','+590',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Guam','GU','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Guatemala','GT','+502',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Guernsey','GG','',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Guinea','GN','+224',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Guinea-Bissau','GW','+245',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Guyana','GY','+592',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Haiti','HT','+509',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Heard Island and McDonald Islands','HM','',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Honduras','HN','+504',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Hong Kong','HK','+852',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Hungary','HU','+36',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Iceland','IS','+354',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'India','IN','+91',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Indonesia','ID','+62',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Iran','IR','+98',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Iraq','IQ','+964',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Ireland','IE','+353',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Isle of Man','IM','',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Israel','IL','+972',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Italy','IT','+39',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Jamaica','JM','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Japan','JP','+81',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Jersey','JE','+44',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Jordan','JO','+962',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Kazakhstan','KZ','+7',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Kenya','KE','+254',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Kiribati','KI','+686',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Kosovo','XK','+383',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Kuwait','KW','+965',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Kyrgyzstan','KG','+996',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Laos','LA','+856',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Latvia','LV','+371',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Lebanon','LB','+961',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Lesotho','LS','+266',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Liberia','LR','+231',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Libya','LY','+218',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Liechtenstein','LI','+423',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Lithuania','LT','+370',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Luxembourg','LU','+352',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Macao','MO','+853',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Macedonia','MK','+389',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Madagascar','MG','+261',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Malawi','MW','+265',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Malaysia','MY','+60',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Maldives','MV','+960',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Mali','ML','+223',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Malta','MT','+356',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Marshall Islands','MH','+692',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Martinique','MQ','+596',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Mauritania','MR','+222',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Mauritius','MU','+230',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Mayotte','YT','+262',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Mexico','MX','+52',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Micronesia','FM','+691',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Moldova','MD','+373',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Monaco','MC','+377',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Mongolia','MN','+976',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Montenegro','ME','+382',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Montserrat','MS','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Morocco','MA','+212',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Mozambique','MZ','+258',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Myanmar','MM','+95',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Namibia','NA','+264',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Nauru','NR','+674',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Nepal','NP','+977',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Netherlands','NL','+31',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'New Caledonia','NC','+687',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'New Zealand','NZ','+64',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Nicaragua','NI','+505',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Niger','NE','+227',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Nigeria','NG','+234',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Niue','NU','+683',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Norfolk Island','NF','+672',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'North Korea','KP','+850',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Northern Mariana Islands','MP','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Norway','NO','+47',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Oman','OM','+968',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Pakistan','PK','+92',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Palau','PW','+680',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Palestinian Territory','PS','+970',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Panama','PA','+507',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Papua New Guinea','PG','+675',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Paraguay','PY','+595',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Peru','PE','+51',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Philippines','PH','+63',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Pitcairn','PN','',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Poland','PL','+48',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Portugal','PT','+351',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Puerto Rico','PR','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Qatar','QA','+974',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Reunion','RE','+262',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Romania','RO','+40',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Russia','RU','+7',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Rwanda','RW','+250',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Saint Barthelemy','BL','+590',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Saint Helena','SH','+290',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Saint Kitts and Nevis','KN','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Saint Lucia','LC','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Saint Martin','MF','+590',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Saint Pierre and Miquelon','PM','+508',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Saint Vincent and the Grenadines','VC','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Samoa','WS','+685',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'San Marino','SM','+378',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Sao Tome and Principe','ST','+239',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Saudi Arabia','SA','+966',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Senegal','SN','+221',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Serbia','RS','+381',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Seychelles','SC','+248',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Sierra Leone','SL','+232',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Singapore','SG','+65',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Sint Maarten','SX','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Slovakia','SK','+421',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Slovenia','SI','+386',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Solomon Islands','SB','+677',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Somalia','SO','+252',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'South Africa','ZA','+27',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'South Georgia and the South Sandwich Islands','GS','',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'South Korea','KR','+82',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'South Sudan','SS','+211',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Spain','ES','+34',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Sri Lanka','LK','+94',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Sudan','SD','+249',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Suriname','SR','+597',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Svalbard and Jan Mayen','SJ','+47',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Swaziland','SZ','+268',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Sweden','SE','+46',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Switzerland','CH','+41',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Syria','SY','+963',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Taiwan','TW','+886',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Tajikistan','TJ','+992',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Tanzania','TZ','+255',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Thailand','TH','+66',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Timor-Leste','TL','+670',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Togo','TG','+228',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Tokelau','TK','+690',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Tonga','TO','+676',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Trinidad and Tobago','TT','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Tunisia','TN','+216',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Turkey','TR','+90',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Turkmenistan','TM','+993',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Turks and Caicos Islands','TC','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Tuvalu','TV','+688',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Uganda','UG','+256',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Ukraine','UA','+380',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'United Arab Emirates','AE','+971',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'United Kingdom','GB','+44',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'United States','US','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Uruguay','UY','+598',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Uzbekistan','UZ','+998',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Vanuatu','VU','+678',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Vatican','VA','+39',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Venezuela','VE','+58',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Vietnam','VN','+84',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Wallis and Futuna','WF','+681',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Western Sahara','EH','+212',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Yemen','YE','+967',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Zambia','ZM','+260',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Zimbabwe','ZW','+263',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Democratic Republic of the Congo','CD','+243',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'United States Minor Outlying Islands','UM','+1',0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Virgin Islands, British','VG','+1 284', 0);
INSERT INTO Countries(Id,CountryName,CountryCode,DialCode,IsDeleted) VALUES (newId(),'Virgin Islands, US','VI','+1 340',0);