INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Afghanistan','AF',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Aland Islands','AX',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Albania','AL',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Algeria','DZ',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'American Samoa','AS',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Andorra','AD',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Angola','AO',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Anguilla','AI',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Antarctica','AQ',0 ) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Antigua and Barbuda','AG',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Argentina','AR',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Armenia','AM',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Aruba','AW',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Australia','AU',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Austria','AT',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Azerbaijan','AZ',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Bahamas','BS',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Bahrain','BH',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Bangladesh','BD',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Barbados','BB',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Belarus','BY',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Belgium','BE',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Belize','BZ',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Benin','BJ',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Bermuda','BM',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Bhutan','BT',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Bolivia','BO',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Bonaire, Sint Eustatius and Saba','BQ',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Bosnia and Herzegovina','BA',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Botswana','BW',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Bouvet Island','BV',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Brazil','BR',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'British Indian Ocean Territory','IO',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Brunei','BN',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Bulgaria','BG',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Burkina Faso','BF',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Burundi','BI',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Cambodia','KH',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Cameroon','CM',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Canada','CA',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Cape Verde','CV',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Cayman Islands','KY',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Central African Republic','CF',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Chad','TD',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Chile','CL',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'China','CN',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Christmas Island','CX',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Cocos (Keeling) Islands','CC',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Colombia','CO',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Comoros','KM',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Congo','CG',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Cook Islands','CK',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Costa Rica','CR',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Ivory Coast','CI',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Croatia','HR',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Cuba','CU','CUB',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Curacao','CW',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Cyprus','CY',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Czech Republic','CZ',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Democratic Republic of the Congo','CD',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Denmark','DK',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Djibouti','DJ',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Dominica','DM',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Dominican Republic','DO',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Ecuador','EC',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Egypt','EG',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'El Salvador','SV',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Equatorial Guinea','GQ',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Eritrea','ER',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Estonia','EE',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Ethiopia','ET',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Falkland Islands (Malvinas)','FK',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Faroe Islands','FO',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Fiji','FJ',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Finland','FI',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'France','FR',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'French Guiana','GF',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'French Polynesia','PF',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'French Southern Territories','TF',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Gabon','GA',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Gambia','GM',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Georgia','GE',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Germany','DE',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Ghana','GH',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Gibraltar','GI',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Greece','GR',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Greenland','GL',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Grenada','GD',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Guadaloupe','GP',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Guam','GU',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Guatemala','GT',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Guernsey','GG',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Guinea','GN',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Guinea-Bissau','GW',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Guyana','GY',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Haiti','HT',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Heard Island and McDonald Islands','HM',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Honduras','HN',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Hong Kong','HK',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Hungary','HU',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Iceland','IS',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'India','IN',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Indonesia','ID',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Iran','IR',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Iraq','IQ',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Ireland','IE',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Isle of Man','IM',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Israel','IL',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Italy','IT',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Jamaica','JM',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Japan','JP',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Jersey','JE',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Jordan','JO',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Kazakhstan','KZ',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Kenya','KE',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Kiribati','KI',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Kosovo','XK',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Kuwait','KW',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Kyrgyzstan','KG',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Laos','LA',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Latvia','LV',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Lebanon','LB',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Lesotho','LS',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Liberia','LR',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Libya','LY',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Liechtenstein','LI',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Lithuania','LT',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Luxembourg','LU',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Macao','MO',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Macedonia','MK',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Madagascar','MG',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Malawi','MW',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Malaysia','MY',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Maldives','MV',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Mali','ML',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Malta','MT',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Marshall Islands','MH',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Martinique','MQ',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Mauritania','MR',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Mauritius','MU',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Mayotte','YT',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Mexico','MX',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Micronesia','FM',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Moldava','MD',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Monaco','MC',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Mongolia','MN',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Montenegro','ME',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Montserrat','MS',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Morocco','MA',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Mozambique','MZ',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Myanmar (Burma)','MM',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Namibia','NA',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Nauru','NR',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Nepal','NP',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Netherlands','NL',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'New Caledonia','NC',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'New Zealand','NZ',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Nicaragua','NI',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Niger','NE',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Nigeria','NG',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Niue','NU',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Norfolk Island','NF',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'North Korea','KP',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Northern Mariana Islands','MP',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Norway','NO',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Oman','OM',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Pakistan','PK',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Palau','PW',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Palestine','PS',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Panama','PA',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Papua New Guinea','PG',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Paraguay','PY',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Peru','PE',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Phillipines','PH',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Pitcairn','PN',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Poland','PL',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Portugal','PT',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Puerto Rico','PR',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Qatar','QA',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Reunion','RE',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Romania','RO',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Russia','RU',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Rwanda','RW',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Saint Barthelemy','BL',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Saint Helena','SH',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Saint Kitts and Nevis','KN',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Saint Lucia','LC',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Saint Martin','MF',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Saint Pierre and Miquelon','PM',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Saint Vincent and the Grenadines','VC',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Samoa','WS',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'San Marino','SM',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Sao Tome and Principe','ST',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Saudi Arabia','SA',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Senegal','SN',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Serbia','RS',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Seychelles','SC',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Sierra Leone','SL',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Singapore','SG',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Sint Maarten','SX',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Slovakia','SK',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Slovenia','SI',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Solomon Islands','SB',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Somalia','SO',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'South Africa','ZA',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'South Georgia and the South Sandwich Islands','GS',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'South Korea','KR',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'South Sudan','SS',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Spain','ES',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Sri Lanka','LK',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Sudan','SD',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Suriname','SR',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Svalbard and Jan Mayen','SJ',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Swaziland','SZ',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Sweden','SE',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Switzerland','CH',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Syria','SY',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Taiwan','TW',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Tajikistan','TJ',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Tanzania','TZ',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Thailand','TH',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Timor-Leste (East Timor)','TL',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Togo','TG',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Tokelau','TK',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Tonga','TO',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Trinidad and Tobago','TT',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Tunisia','TN',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Turkey','TR',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Turkmenistan','TM',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Turks and Caicos Islands','TC',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Tuvalu','TV',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Uganda','UG',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Ukraine','UA',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'United Arab Emirates','AE',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'United Kingdom','GB',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'United States','US',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'United States Minor Outlying Islands','UM',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Uruguay','UY',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Uzbekistan','UZ',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Vanuatu','VU',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Vatican City','VA',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Venezuela','VE',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Vietnam','VN',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Virgin Islands, British','VG',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Virgin Islands, US','VI',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Wallis and Futuna','WF',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Western Sahara','EH',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Yemen','YE',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Zambia','ZM',0) ;
INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES (newId(),'Zimbabwe','ZW',0); ;

