INSERT INTO Countries(Id,CountryName,CountryCode,IsDeleted) VALUES 
(newId(),'Afghanistan','AF',0)
,(newId(),'Aland Islands','AX',0)
,(newId(),'Albania','AL',0)
,(newId(),'Algeria','DZ',0)
,(newId(),'American Samoa','AS',0)
,(newId(),'Andorra','AD',0)
,(newId(),'Angola','AO',0)
,(newId(),'Anguilla','AI',0)
,(newId(),'Antarctica','AQ',0 )
,(newId(),'Antigua and Barbuda','AG',0)
,(newId(),'Argentina','AR',0)
,(newId(),'Armenia','AM',0)
,(newId(),'Aruba','AW',0)
,(newId(),'Australia','AU',0)
,(newId(),'Austria','AT',0)
,(newId(),'Azerbaijan','AZ',0)
,(newId(),'Bahamas','BS',0)
,(newId(),'Bahrain','BH',0)
,(newId(),'Bangladesh','BD',0)
,(newId(),'Barbados','BB',0)
,(newId(),'Belarus','BY',0)
,(newId(),'Belgium','BE',0)
,(newId(),'Belize','BZ',0)
,(newId(),'Benin','BJ',0)
,(newId(),'Bermuda','BM',0)
,(newId(),'Bhutan','BT',0)
,(newId(),'Bolivia','BO',0)
,(newId(),'Bonaire, Sint Eustatius and Saba','BQ',0)
,(newId(),'Bosnia and Herzegovina','BA',0)
,(newId(),'Botswana','BW',0)
,(newId(),'Bouvet Island','BV',0)
,(newId(),'Brazil','BR',0)
,(newId(),'British Indian Ocean Territory','IO',0)
,(newId(),'Brunei','BN',0)
,(newId(),'Bulgaria','BG',0)
,(newId(),'Burkina Faso','BF',0)
,(newId(),'Burundi','BI',0)
,(newId(),'Cambodia','KH',0)
,(newId(),'Cameroon','CM',0)
,(newId(),'Canada','CA',0)
,(newId(),'Cape Verde','CV',0)
,(newId(),'Cayman Islands','KY',0)
,(newId(),'Central African Republic','CF',0)
,(newId(),'Chad','TD',0)
,(newId(),'Chile','CL',0)
,(newId(),'China','CN',0)
,(newId(),'Christmas Island','CX',0)
,(newId(),'Cocos (Keeling) Islands','CC',0)
,(newId(),'Colombia','CO',0)
,(newId(),'Comoros','KM',0)
,(newId(),'Congo','CG',0)
,(newId(),'Cook Islands','CK',0)
,(newId(),'Costa Rica','CR',0)
,(newId(),'Ivory Coast','CI',0)
,(newId(),'Croatia','HR',0)
,(newId(),'Cuba','CU','CUB',0)
,(newId(),'Curacao','CW',0)
,(newId(),'Cyprus','CY',0)
,(newId(),'Czech Republic','CZ',0)
,(newId(),'Democratic Republic of the Congo','CD',0)
,(newId(),'Denmark','DK',0)
,(newId(),'Djibouti','DJ',0)
,(newId(),'Dominica','DM',0)
,(newId(),'Dominican Republic','DO',0)
,(newId(),'Ecuador','EC',0)
,(newId(),'Egypt','EG',0)
,(newId(),'El Salvador','SV',0)
,(newId(),'Equatorial Guinea','GQ',0)
,(newId(),'Eritrea','ER',0)
,(newId(),'Estonia','EE',0)
,(newId(),'Ethiopia','ET',0)
,(newId(),'Falkland Islands (Malvinas)','FK',0)
,(newId(),'Faroe Islands','FO',0)
,(newId(),'Fiji','FJ',0)
,(newId(),'Finland','FI',0)
,(newId(),'France','FR',0)
,(newId(),'French Guiana','GF',0)
,(newId(),'French Polynesia','PF',0)
,(newId(),'French Southern Territories','TF',0)
,(newId(),'Gabon','GA',0)
,(newId(),'Gambia','GM',0)
,(newId(),'Georgia','GE',0)
,(newId(),'Germany','DE',0)
,(newId(),'Ghana','GH',0)
,(newId(),'Gibraltar','GI',0)
,(newId(),'Greece','GR',0)
,(newId(),'Greenland','GL',0)
,(newId(),'Grenada','GD',0)
,(newId(),'Guadaloupe','GP',0)
,(newId(),'Guam','GU',0)
,(newId(),'Guatemala','GT',0)
,(newId(),'Guernsey','GG',0)
,(newId(),'Guinea','GN',0)
,(newId(),'Guinea-Bissau','GW',0)
,(newId(),'Guyana','GY',0)
,(newId(),'Haiti','HT',0)
,(newId(),'Heard Island and McDonald Islands','HM',0)
,(newId(),'Honduras','HN',0)
,(newId(),'Hong Kong','HK',0)
,(newId(),'Hungary','HU',0)
,(newId(),'Iceland','IS',0)
,(newId(),'India','IN',0)
,(newId(),'Indonesia','ID',0)
,(newId(),'Iran','IR',0)
,(newId(),'Iraq','IQ',0)
,(newId(),'Ireland','IE',0)
,(newId(),'Isle of Man','IM',0)
,(newId(),'Israel','IL',0)
,(newId(),'Italy','IT',0)
,(newId(),'Jamaica','JM',0)
,(newId(),'Japan','JP',0)
,(newId(),'Jersey','JE',0)
,(newId(),'Jordan','JO',0)
,(newId(),'Kazakhstan','KZ',0)
,(newId(),'Kenya','KE',0)
,(newId(),'Kiribati','KI',0)
,(newId(),'Kosovo','XK',0)
,(newId(),'Kuwait','KW',0)
,(newId(),'Kyrgyzstan','KG',0)
,(newId(),'Laos','LA',0)
,(newId(),'Latvia','LV',0)
,(newId(),'Lebanon','LB',0)
,(newId(),'Lesotho','LS',0)
,(newId(),'Liberia','LR',0)
,(newId(),'Libya','LY',0)
,(newId(),'Liechtenstein','LI',0)
,(newId(),'Lithuania','LT',0)
,(newId(),'Luxembourg','LU',0)
,(newId(),'Macao','MO',0)
,(newId(),'Macedonia','MK',0)
,(newId(),'Madagascar','MG',0)
,(newId(),'Malawi','MW',0)
,(newId(),'Malaysia','MY',0)
,(newId(),'Maldives','MV',0)
,(newId(),'Mali','ML',0)
,(newId(),'Malta','MT',0)
,(newId(),'Marshall Islands','MH',0)
,(newId(),'Martinique','MQ',0)
,(newId(),'Mauritania','MR',0)
,(newId(),'Mauritius','MU',0)
,(newId(),'Mayotte','YT',0)
,(newId(),'Mexico','MX',0)
,(newId(),'Micronesia','FM',0)
,(newId(),'Moldava','MD',0)
,(newId(),'Monaco','MC',0)
,(newId(),'Mongolia','MN',0)
,(newId(),'Montenegro','ME',0)
,(newId(),'Montserrat','MS',0)
,(newId(),'Morocco','MA',0)
,(newId(),'Mozambique','MZ',0)
,(newId(),'Myanmar (Burma)','MM',0)
,(newId(),'Namibia','NA',0)
,(newId(),'Nauru','NR',0)
,(newId(),'Nepal','NP',0)
,(newId(),'Netherlands','NL',0)
,(newId(),'New Caledonia','NC',0)
,(newId(),'New Zealand','NZ',0)
,(newId(),'Nicaragua','NI',0)
,(newId(),'Niger','NE',0)
,(newId(),'Nigeria','NG',0)
,(newId(),'Niue','NU',0)
,(newId(),'Norfolk Island','NF',0)
,(newId(),'North Korea','KP',0)
,(newId(),'Northern Mariana Islands','MP',0)
,(newId(),'Norway','NO',0)
,(newId(),'Oman','OM',0)
,(newId(),'Pakistan','PK',0)
,(newId(),'Palau','PW',0)
,(newId(),'Palestine','PS',0)
,(newId(),'Panama','PA',0)
,(newId(),'Papua New Guinea','PG',0)
,(newId(),'Paraguay','PY',0)
,(newId(),'Peru','PE',0)
,(newId(),'Phillipines','PH',0)
,(newId(),'Pitcairn','PN',0)
,(newId(),'Poland','PL',0)
,(newId(),'Portugal','PT',0)
,(newId(),'Puerto Rico','PR',0)
,(newId(),'Qatar','QA',0)
,(newId(),'Reunion','RE',0)
,(newId(),'Romania','RO',0)
,(newId(),'Russia','RU',0)
,(newId(),'Rwanda','RW',0)
,(newId(),'Saint Barthelemy','BL',0)
,(newId(),'Saint Helena','SH',0)
,(newId(),'Saint Kitts and Nevis','KN',0)
,(newId(),'Saint Lucia','LC',0)
,(newId(),'Saint Martin','MF',0)
,(newId(),'Saint Pierre and Miquelon','PM',0)
,(newId(),'Saint Vincent and the Grenadines','VC',0)
,(newId(),'Samoa','WS',0)
,(newId(),'San Marino','SM',0)
,(newId(),'Sao Tome and Principe','ST',0)
,(newId(),'Saudi Arabia','SA',0)
,(newId(),'Senegal','SN',0)
,(newId(),'Serbia','RS',0)
,(newId(),'Seychelles','SC',0)
,(newId(),'Sierra Leone','SL',0)
,(newId(),'Singapore','SG',0)
,(newId(),'Sint Maarten','SX',0)
,(newId(),'Slovakia','SK',0)
,(newId(),'Slovenia','SI',0)
,(newId(),'Solomon Islands','SB',0)
,(newId(),'Somalia','SO',0)
,(newId(),'South Africa','ZA',0)
,(newId(),'South Georgia and the South Sandwich Islands','GS',0)
,(newId(),'South Korea','KR',0)
,(newId(),'South Sudan','SS',0)
,(newId(),'Spain','ES',0)
,(newId(),'Sri Lanka','LK',0)
,(newId(),'Sudan','SD',0)
,(newId(),'Suriname','SR',0)
,(newId(),'Svalbard and Jan Mayen','SJ',0)
,(newId(),'Swaziland','SZ',0)
,(newId(),'Sweden','SE',0)
,(newId(),'Switzerland','CH',0)
,(newId(),'Syria','SY',0)
,(newId(),'Taiwan','TW',0)
,(newId(),'Tajikistan','TJ',0)
,(newId(),'Tanzania','TZ',0)
,(newId(),'Thailand','TH',0)
,(newId(),'Timor-Leste (East Timor)','TL',0)
,(newId(),'Togo','TG',0)
,(newId(),'Tokelau','TK',0)
,(newId(),'Tonga','TO',0)
,(newId(),'Trinidad and Tobago','TT',0)
,(newId(),'Tunisia','TN',0)
,(newId(),'Turkey','TR',0)
,(newId(),'Turkmenistan','TM',0)
,(newId(),'Turks and Caicos Islands','TC',0)
,(newId(),'Tuvalu','TV',0)
,(newId(),'Uganda','UG',0)
,(newId(),'Ukraine','UA',0)
,(newId(),'United Arab Emirates','AE',0)
,(newId(),'United Kingdom','GB',0)
,(newId(),'United States','US',0)
,(newId(),'United States Minor Outlying Islands','UM',0)
,(newId(),'Uruguay','UY',0)
,(newId(),'Uzbekistan','UZ',0)
,(newId(),'Vanuatu','VU',0)
,(newId(),'Vatican City','VA',0)
,(newId(),'Venezuela','VE',0)
,(newId(),'Vietnam','VN',0)
,(newId(),'Virgin Islands, British','VG',0)
,(newId(),'Virgin Islands, US','VI',0)
,(newId(),'Wallis and Futuna','WF',0)
,(newId(),'Western Sahara','EH',0)
,(newId(),'Yemen','YE',0)
,(newId(),'Zambia','ZM',0)
,(newId(),'Zimbabwe','ZW',0);