namespace AddOptimization.Utilities.Constants;

public class ValidationCodes
{
    public const string EmailNotExists = "EmailNotExists";
    public const string EmailUserNameAlreadyExists = "EmailUserNameAlreadyExists";
    public const string AppSettingAlreadyExists = "AppSettingAlreadyExists";
    public const string InvalidToken = "InvalidToken";
    public const string InvalidPassword = "InvalidPassword";
    public const string InvalidUserName = "InvalidUserName";
    public const string InactiveUserAccount = "InactiveUserAccount";
    public const string LockedUserAccount = "LockedUserAccount";
    public const string UserAccountLockedDueToFailedAttamps = "UserAccountLockedDueToFailedAttamps";
    public const string PasswordResetLinkLimitReached = "PasswordResetLinkLimitReached";
    public const string IssueSendingEmail = "IssueSendingEmail";
    public const string CategoryKeyAlreadyExists = "CategoryKeyAlreadyExists";
    public const string DepartmentUsersExists = "DepartmentUsersExists";
    public const string FieldNameAlreadyExists = "FieldNameAlreadyExists";
    public const string SelectAtleastOneAction = "SelectAtleastOneAction";
    public const string PropertyValueAlreadyExists = "PropertyValueAlreadyExists";
    public const string SearchWithNameAlreadyExists = "SearchWithNameAlreadyExists";
    public const string SearchAcrossBranchCantEdited = "SearchAcrossBranchCantEdited";
    public const string OtherUserSearchDelete = "OtherUserSearchDelete";
    public const string ScreenWithNameAlreadyExists = "ScreenWithNameAlreadyExists";
    public const string ThreadIdRequired = "ThreadIdRequired";
    public const string PasswordResetLinkExpired = "PasswordResetLinkExpired";
    public const string InternalServerError = "InternalServerError";
    public const string PermissionDenied = "PermissionDenied";
    public const string TagInUseDeleteNotAllowed = "TagInUseDeleteNotAllowed";
    public const string RoleInUseDeleteNotAllowed = "RoleInUseDeleteNotAllowed";
    public const string SystemRoleModificationNotAllowed = "SystemRoleModificationNotAllowed";
    public const string StripeError = "StripeError";
    public const string ServerError = "ServerError";
    public const string OrderLineItemRequired = "OrderLineItemRequired";
    public const string OnlyInvoicedOrdersCopy = "OnlyInvoicedOrdersCopy";
    public const string OrderThresholdReached = "OrderThresholdReached";
    public const string OrderInprogressRequiredFields = "OrderInprogressRequiredFields";
    public const string CannotActivateLicense = "CannotActivateLicense";
    public const string InvalidLicense = "InvalidLicense";
    public const string AbsenceRequestedProhibited = "AbsenceRequestedProhibited";
    public const string CustomerEmployeeAssociationAlreadyExists = "CustomerEmployeeAssociationAlreadyExists";
    public const string SchedulerEventsDoesNotExists = "SchedulerEventsDoesNotExists";
    public const string EmployeeAlreadyExists = "EmployeeAlreadyExists";
    public const string LoginWithMicrosoftProvider = "LoginWithMicrosoftProvider";
    public const string NotFound = "CustomerEmployeeAssociationNotFound";
    public const string FolderAlreadyExists = "FolderAlreadyExist";
    public const string GroupAlreadyExists = "GroupAlreadyExists";
    public const string EmailNotificationSettingIsDisabled = "EmailNotificationSettingIsDisabled";
    public const string UnpaidInvoiceDoesNotExists = "UnpaidInvoiceDoesNotExists";
    public const string DataNoLongerExist = "DataNoLongerExist";
}
